import test from 'node:test';
import assert from 'node:assert/strict';
import {evaluate,formatResult} from '../dist/calculator-engine.js';
import {sequence,fields,insert,navigate,serialize,exitStructure,unwrapEmpty} from '../dist/calculator-tree.js';
test('shared engine precedence, negatives, exact decimals and Ans',()=>{for(const[s,n]of[['2+3*4',14],['(3+5)/2',4],['-2^2',-4],['2^-3',.125],['2^3^2',512],['5!',120],['50%',.5],['abs(-8)',8]])assert.equal(evaluate(s).value,n);assert.equal(formatResult(evaluate('0.1+0.2'),true),'3/10');assert.equal(formatResult(evaluate('25/2'),true),'25/2');assert.equal(evaluate('Ans*2',{ans:evaluate('25/2')}).value,25);});
test('scientific functions and errors',()=>{assert.ok(Math.abs(evaluate('sin(30)').value-.5)<1e-12);assert.ok(Math.abs(evaluate('sin(pi/2)',{angle:'RAD'}).value-1)<1e-12);assert.ok(Math.abs(evaluate('asin(0.5)').value-30)<1e-10);for(const[s,n]of[['sqrt(25)',5],['root(3,-8)',-2],['log(100)',2],['ln(e)',1],['3×10^4',30000]])assert.equal(evaluate(s).value,n);for(const s of['1/0','sqrt(-1)','log(0)','tan(90)','(-1)!','1+','sin(2,3)','alert(1)','1e999'])assert.throws(()=>evaluate(s));assert.equal(evaluate('sin(30)').exact,null);});
test('structured fraction editing, nested power, navigation and serialization',()=>{const tree=sequence(),first=fields(tree)[0].id;const top=insert(tree,first,0,0,'Fraction');fields(tree).find(f=>f.id===top).text='25';const bottom=navigate(tree,top,'down');assert.notEqual(top,bottom);fields(tree).find(f=>f.id===bottom).text='2';assert.equal(navigate(tree,bottom,'up'),top);assert.equal(evaluate(serialize(tree)).value,12.5);assert.equal(serialize(JSON.parse(JSON.stringify(tree))),serialize(tree));const power=insert(tree,bottom,1,1,'Power');fields(tree).find(f=>f.id===power).text='2';assert.equal(evaluate(serialize(tree)).value,6.25);assert.notEqual(navigate(tree,power,'right'),power);});
test('empty structures unwrap safely',()=>{const tree=sequence();const id=insert(tree,fields(tree)[0].id,0,0,'Sqrt');assert.equal(unwrapEmpty(tree,id),true);assert.equal(serialize(tree),'');});

test('closing a natural group exits to its following expression field',()=>{const tree=sequence();const body=insert(tree,fields(tree)[0].id,0,0,'Group');fields(tree).find(f=>f.id===body).text='3+5';const after=exitStructure(tree,body);assert.notEqual(after,body);fields(tree).find(f=>f.id===after).text='/2';assert.equal(evaluate(serialize(tree)).value,4);});
