import {test} from 'node:test';
import assert from 'node:assert/strict';
import {createGraph,shiftAxis,changeExtent,canChangeExtent,associateGraph,attachGraphContents,graphContents,resizeGraph,transformGraphContents} from '../dist/graph-model.js';
import {createObject,newDocument,DocumentStore,validateDocument} from '../dist/core.js';
import {planeMetrics,localToWorld} from '../dist/geometry.js';
import {renderObject} from '../dist/render.js';
import {renderGraphScene} from '../dist/graph-render.js';
import {compileRelation,drawFunctions} from '../dist/algebra.js';
const close=(a,b)=>assert.ok(Math.abs(a-b)<1e-8,`${a} != ${b}`);
function point(o,x,y){const m=planeMetrics(o);return localToWorld({x:m.origin.x+x*m.unit,y:m.origin.y-y*m.unit},o);}
function recorder(){const calls=[];return {calls,ctx:new Proxy({globalAlpha:1,measureText:()=>({width:20})},{get:(t,k)=>k in t?t[k]:(...args)=>calls.push([k,...args]),set:(t,k,v)=>(t[k]=v,calls.push(['set',k,v]),true)})};}
test('new paper is a centred 9 by 13 detailed grid, axis pad moves exactly one major square',()=>{const g=createGraph({x:100,y:200}),m=planeMetrics(g);assert.equal(g.grid,'detailed');close(g.xMax-g.xMin,9);close(g.yMax-g.yMin,13);close(m.origin.x,g.width/2);close(m.origin.y,g.height/2);for(const [dir,dx,dy]of[['left',-40,0],['right',40,0],['up',0,-40],['down',0,40]]){const copy=structuredClone(g);shiftAxis(copy,dir);const n=planeMetrics(copy);close(n.origin.x-m.origin.x,dx);close(n.origin.y-m.origin.y,dy);close(n.unit,m.unit);}});
test('extent controls preserve square spacing and retained coordinate positions even after rotation/scale',()=>{for(const dir of ['left','right','up','down']){const g=createGraph({x:20,y:70});g.rotation=.4;g.scale={x:1.7,y:1.7};const before=point(g,1,2),unit=planeMetrics(g).unit;assert.ok(changeExtent(g,dir));const after=point(g,1,2);close(before.x,after.x);close(before.y,after.y);close(unit,planeMetrics(g).unit);}const g=createGraph({x:0,y:0});while(canChangeExtent(g,'left'))changeExtent(g,'left');assert.equal(g.xMax-g.xMin,1);assert.equal(changeExtent(g,'left'),false);});
test('separate sparse ink associates by intersection, transforms proportionally and survives crop/history/reopen',()=>{const g=createGraph({x:0,y:0}),ink=createObject('InkStroke',{position:{x:-100,y:200},points:[{x:0,y:0,pressure:.3},{x:700,y:0,pressure:.9}],strokeWidth:4}),text=createObject('TextObject',{position:{x:90,y:100},text:'y = x²',fontSize:20,fontFamily:'sans-serif',width:100,height:30}),outside=createObject('InkStroke',{position:{x:900,y:900},points:[{x:0,y:0},{x:50,y:50}]});const objects=[g,ink,text,outside];associateGraph(ink,objects);assert.equal(ink.graphId,g.id);attachGraphContents(objects,g);assert.equal(text.graphId,g.id);assert.equal(outside.graphId,undefined);const before=structuredClone(objects);resizeGraph(g,before[0],{x:0,y:0},2);transformGraphContents(objects,before,before[0],g);close(ink.position.x,-200);close(ink.position.y,400);close(ink.scale.x,2);close(text.scale.y,2);assert.equal(ink.strokeWidth,4);assert.equal(ink.points[1].pressure,.9);assert.deepEqual(outside,before[3]);const store=new DocumentStore({...newDocument(),objects});store.transact(d=>changeExtent(d.objects[0],'left'));assert.deepEqual(store.document.objects[1],ink);store.undo();assert.equal(store.document.objects[0].xMin,-4.5);store.redo();assert.equal(store.document.objects[0].xMin,-3.5);assert.ok(validateDocument(JSON.parse(JSON.stringify(store.document))));assert.deepEqual(graphContents(objects,g).map(o=>o.id),[g.id,ink.id,text.id]);});
test('strict vertical inequality is dotted, inclusive solid, numerical parsing remains unchanged',()=>{const g=createGraph({x:0,y:0});for(const [source,dash]of[['x<2',[.01,5]],['x≤2',[]]]){g.functions=[{id:'f',source,colour:'#2563eb',visible:true}];const {ctx,calls}=recorder();drawFunctions(ctx,g,planeMetrics(g));assert.ok(calls.some(c=>c[0]==='setLineDash'&&JSON.stringify(c[1])===JSON.stringify(dash)));const r=compileRelation(source);assert.equal(r.accept(r.difference(1,0)),true);assert.equal(r.accept(r.difference(3,0)),false);assert.ok(calls.some(c=>c[0]==='fillRect'&&c[1]===20));assert.ok(calls.filter(c=>c[0]==='moveTo').length<5,'a continuous boundary must not reset its dot pattern per sample');}for(const [source,x,y]of[['y=x^2',2,4],['y=sin(x)',Math.PI/2,1],['y=1/x',2,.5],['x^2+y^2=4',0,2],['y=2x+1',3,7]]){close(compileRelation(source).difference(x,y),0);}});
test('arrow tips reach grid boundaries, x sits beside tip and terminal ticks do not overlap',()=>{const g=createGraph({x:0,y:0});g.xMin=-4;g.xMax=5;g.yMin=-6;g.yMax=7;const {ctx,calls}=recorder(),m=planeMetrics(g);renderObject(ctx,g,false,()=>{});assert.ok(calls.some(c=>c[0]==='translate'&&c[1]===g.width-m.left&&c[2]===m.origin.y));assert.ok(calls.some(c=>c[0]==='translate'&&c[1]===m.origin.x&&c[2]===m.top));assert.ok(calls.some(c=>c[0]==='fillText'&&c[1]==='x'&&c[2]>g.width-m.left&&c[3]===m.origin.y));assert.ok(!calls.some(c=>c[0]==='fillText'&&c[1]==='5'&&c[2]===g.width-m.left));});
test('graph export compositor includes ink, text and curves in scene order with crop clipping',()=>{const g=createGraph({x:0,y:0}),ink=createObject('InkStroke',{position:{x:40,y:40},points:[{x:0,y:0},{x:30,y:50},{x:80,y:0}],graphId:g.id}),text=createObject('TextObject',{position:{x:80,y:80},width:100,height:30,text:'Answer',fontSize:18,fontFamily:'sans-serif',graphId:g.id});g.functions=[{id:'f',source:'y=x^2',colour:'#397ce9',visible:true}];const {ctx,calls}=recorder();renderGraphScene(ctx,[g,ink,text],false,()=>{});assert.ok(calls.some(c=>c[0]==='quadraticCurveTo'));assert.ok(calls.some(c=>c[0]==='fillText'&&c[1]==='Answer'));assert.ok(calls.filter(c=>c[0]==='clip').length>=3);});
test('copying a complete graph relinks annotations; copying just ink detaches it safely',async()=>{const {copyGraphSelection}=await import('../dist/graph-model.js');const g=createGraph({x:0,y:0}),ink=createObject('InkStroke',{position:{x:20,y:30},points:[{x:0,y:0},{x:20,y:20}],graphId:g.id});const copied=copyGraphSelection([g,ink],[g.id]);assert.equal(copied.length,2);assert.equal(copied[1].graphId,copied[0].id);assert.notEqual(copied[1].graphId,g.id);const only=copyGraphSelection([g,ink],[ink.id]);assert.equal(only[0].graphId,undefined);});
test('continuous graph movement does not mutate the drag baseline or accumulate drift',()=>{const g=createGraph({x:0,y:0}),ink=createObject('InkStroke',{position:{x:40,y:60},points:[{x:0,y:0},{x:20,y:30}],graphId:g.id}),baseline=[g,ink];for(const delta of [10,20,30]){const moved={...g,position:{x:delta,y:delta}},frame=[moved,ink];transformGraphContents(frame,baseline,g,moved);close(frame[1].position.x,40+delta);close(frame[1].position.y,60+delta);close(baseline[1].position.x,40);close(baseline[1].position.y,60);}});
