import test from 'node:test';import assert from 'node:assert/strict';
import {NaturalEditor,fields,serialize,boundaryField,children} from '../dist/calculator-tree.js';
import {evaluate} from '../dist/calculator-engine.js';
import {PolygonProof,nextDiagonal} from '../dist/polygon-proof.js';
import {LabelLayout,edgeCandidates,polarCandidates} from '../dist/label-layout.js';
const near=(a,b)=>assert.ok(Math.abs(a-b)<1e-9,`${a} ≠ ${b}`);
function run(keys){const editor=new NaturalEditor();for(const k of keys)editor.key(k);return editor;}
const value=keys=>evaluate(serialize(run(keys).root)).value;
test('a blank fraction has only two template slots; surrounding caret gaps are not placeholders',()=>{const e=run(['a/b']),fraction=e.root.children.find(n=>n.type==='Fraction');assert.deepEqual(Object.keys(fraction).sort(),['denominator','numerator','type']);let count=0;function visit(n,parent){if(n.type==='Text'&&!boundaryField(parent,n))count++;children(n).forEach(c=>visit(c,n));}visit(e.root);assert.equal(count,2);assert.equal(e.id,fields(fraction.numerator)[0].id);e.key('↓');assert.equal(e.id,fields(fraction.denominator)[0].id);e.key('→');assert.equal(e.id,e.root.children.at(-1).id);});
test('requested textbook examples and nested fractions calculate correctly',()=>{near(value(['a/b','3','↓','4','OUT','+','5']),5.75);near(value(['2','+','a/b','3','↓','4','+','5','OUT']),2+3/9);near(value(['√','3','+','a/b','2','↓','5','OUT','OUT']),Math.sqrt(3.4));near(value(['a/b','1','↓','a/b','2','↓','3','OUT','OUT']),1.5);near(value(['mixed','2','→','1','↓','3','OUT']),7/3);near(value(['mixed','-','2','→','1','↓','3','OUT']),-7/3);});
test('powers capture the preceding operand, including structured operands, not the entire sum',()=>{near(value(['2','+','3','x²']),11);near(value(['(','2','+','3',')','x²']),25);near(value(['a/b','3','↓','4','OUT','x²']),.5625);near(value(['2','xʸ','3','OUT','+','4']),12);near(value(['xʸ','2','↑','3','OUT']),8);});
test('all natural mathematical keys evaluate in valid constructions',()=>{const cases=[
 [['√','9','OUT'],3],[['ⁿ√','3','↓','2','7','OUT'],3],[['2','x³'],8],[['4','1/x'],.25],
 [['sin','3','0',')'],.5],[['cos','6','0',')'],.5],[['tan','4','5',')'],1],
 [['asin','0','.','5',')'],30],[['acos','0','.','5',')'],60],[['atan','1',')'],45],
 [['log','1','0','0',')'],2],[['ln','e',')'],1],[['abs','±','3',')'],3],
 [['10ˣ','2','OUT'],100],[['eˣ','1','OUT'],Math.E],[['3','×10ⁿ','2','OUT'],300],
 [['3','±'],-3],[['±','3'],-3],[['3','±','±'],3],[['2','-','3','±'],5],[['2','−','3','±'],5],[['2','-','3','±','±'],-1],[['a/b','3','↓','4','OUT','±'],-.75],[['a/b','3','↓','4','OUT','±','±'],.75],[['(','2','+','3',')','×','4'],20],
 [['7','−','2'],5],[['8','÷','4'],2],[['5','!'],120],[['5','0','%'],.5],[['π'],Math.PI],
 [['a/b','1','↓','2','OUT','+','a/b','3','↓','4','OUT'],1.25]
 ];for(const [keys,n]of cases)near(value(keys),n);const e=run(['9','C','1','DEL','2']);near(evaluate(serialize(e.root)).value,2);near(evaluate(serialize(run(['Ans','×','2']).root),{ans:5}).value,10);});
test('nested navigation, deletion and malformed input remain recoverable',()=>{const e=run(['√','a/b']);const innerId=e.id;e.key('↓');e.key('↑');assert.equal(e.id,innerId);e.key('DEL');assert.equal(e.root.children[1].type,'Sqrt');assert.equal(serialize(e.root),'sqrt()');assert.throws(()=>evaluate(serialize(e.root)));e.key('9');e.key('OUT');near(evaluate(serialize(e.root)).value,3);e.key('←');e.key('DEL');e.key('4');e.key('OUT');near(evaluate(serialize(e.root)).value,2);e.key('C');e.type('123');e.focus(e.id,1);e.remove(true);assert.equal(serialize(e.root),'13');e.key('DEL');assert.equal(serialize(e.root),'3');});
test('triangle numbers survive later cuts and vertex edits; regeneration resets identity',()=>{const m=new PolygonProof(10),seen=new Map();while(!m.state.complete){const cut=nextDiagonal(m.points,m.cuts);m.add(...cut);for(const t of m.triangles){if(seen.has(t.key))assert.equal(t.id,seen.get(t.key));seen.set(t.key,t.id);}}assert.equal(m.triangles.length,8);assert.deepEqual(m.triangles.map(t=>t.id),[1,2,3,4,5,6,7,8]);m.move(0,{x:m.points[0].x+2,y:m.points[0].y});for(const t of m.triangles)assert.equal(t.id,seen.get(t.key));m.scrub(1);m.reset(5);assert.equal(m.progress,0);assert.equal(m.cuts.length,0);assert.equal(m.triangleIds.size,0);});
test('label placement flips a blocked side and avoids nearby labels with stable candidates',()=>{const layout=new LabelLayout(),a={x:50,y:100},b={x:180,y:100},candidates=edgeCandidates(a,b);layout.begin({bounds:{x:0,y:0,w:250,h:200},segments:[[a,b],...[50,58,66,74,82,90].map(y=>[{x:65,y},{x:165,y}])],points:[]});const label=layout.place({id:'side',text:'5 cm',width:32,candidates});assert.ok(label.y>100);layout.end();layout.begin({bounds:{x:0,y:0,w:250,h:200},segments:[[a,b],...[50,58,66,74,81,90].map(y=>[{x:65,y},{x:165,y}])]});const again=layout.place({id:'side',text:'5 cm',width:32,candidates});assert.equal(again.y,label.y);const next=layout.place({id:'angle',text:'45°',width:30,candidates:polarCandidates({x:115,y:100},Math.PI/2,18)});assert.ok(Math.hypot(next.x-again.x,next.y-again.y)>15);assert.ok(Math.hypot(again.x-115,again.y-100)<60);});

test('near-edge labels stay inside the viewport without wandering',()=>{const layout=new LabelLayout();layout.begin({bounds:{x:6,y:6,w:188,h:188}});const label=layout.place({id:'vertex',text:'A',width:12,candidates:polarCandidates({x:15,y:80},Math.PI,23)});assert.ok(label.x>=15&&label.x<=185);assert.ok(Math.hypot(label.x-15,label.y-80)<55);});

test('mixed fractions reject a non-integer whole part instead of giving a misleading value',()=>{assert.throws(()=>evaluate(serialize(run(['mixed','2','.','5','→','1','↓','3','OUT']).root)));assert.throws(()=>evaluate(serialize(run(['mixed','-','2','+','3','→','1','↓','3','OUT']).root)));near(value(['mixed','-','2','.','0','→','1','↓','3','OUT']),-7/3);});
