import test from 'node:test';import assert from 'node:assert/strict';
import {editMath,validateMath} from '../dist/math-input.js';
import {ToolContinuity} from '../dist/interaction.js';
import {isRightAngle,angleMark} from '../dist/angle-renderer.js';
import {PolygonProof,regularPolygon,triangulation,polygonError,interior,signedArea,anglePieces} from '../dist/polygon-proof.js';
const near=(a,b)=>assert.ok(Math.abs(a-b)<1e-7,`${a} ≠ ${b}`);
test('numeric keypad enforces configured signs, decimals, ranges through one path',()=>{const c={min:0,max:180,allowNegative:false,allowDecimal:true};let s='';for(const k of ['4','5','.','5'])s=editMath(s,k,c);assert.equal(s,'45.5');assert.ok(validateMath(s,c));assert.equal(editMath(s,'-',c),s);assert.equal(editMath(s,'.',c),s);assert.ok(!validateMath('181',c));assert.ok(!validateMath('-1',c));assert.ok(!validateMath('1.5',{...c,allowDecimal:false}));assert.equal(editMath(s,'Backspace',c),'45.');});
test('temporary shape selection preserves tool until empty press; explicit selection cancels it',()=>{const c=new ToolContinuity();c.choose('shapes');c.created('shapes');assert.equal(c.resume(),'shapes');c.created('shapes');c.choose('select');assert.equal(c.resume(),null);c.choose('smart');c.created('smart');assert.equal(c.resume(),'smart');c.choose('eraser');assert.equal(c.resume(),null);});
test('right marker respects tolerance and rotated ray directions',()=>{assert.ok(isRightAngle(Math.PI/2));assert.ok(isRightAngle(-Math.PI/2));assert.ok(!isRightAngle(Math.PI/3));const points=[],ctx={beginPath(){},moveTo(x,y){points.push([x,y])},lineTo(x,y){points.push([x,y])},stroke(){}};assert.equal(angleMark(ctx,{start:.7,sweep:Math.PI/2,radius:20}),false);near(Math.hypot(points[1][0]-points[0][0],points[1][1]-points[0][1]),11);near(Math.hypot(points[2][0]-points[1][0],points[2][1]-points[1][1]),11);});
test('convex and concave polygons triangulate, preserve area and align exact half-turns',()=>{const cases=Array.from({length:18},(_,i)=>regularPolygon(i+3));cases.push([{x:0,y:0},{x:100,y:0},{x:50,y:30},{x:100,y:100},{x:0,y:100}],[{x:0,y:0},{x:100,y:0},{x:10,y:12}]);for(const ps of cases)for(const points of [ps,[...ps].reverse()]){const m=new PolygonProof();m.points=points;m.auto();assert.equal(m.state.complete,true);assert.equal(m.cuts.length,points.length-3);near(m.state.faces.reduce((s,f)=>s+Math.abs(signedArea(f.map(i=>points[i]))),0),Math.abs(signedArea(points)));near(points.reduce((s,_,i)=>s+interior(points,i).degrees,0),(points.length-2)*180);for(const face of m.state.faces){const pieces=anglePieces(points,face,1,{x:650,y:100});near(pieces.reduce((s,p)=>s+p.sweep,0),Math.PI);near(Math.sin(pieces[0].start),0);for(let i=1;i<3;i++)near(Math.sin(pieces[i-1].start+pieces[i-1].sweep-pieces[i].start),0);for(const p of pieces){near(p.p.x,650);near(p.p.y,100);}}}});
test('reject crossing/exterior cuts and invalid shapes; incomplete proof stays locked',()=>{const m=new PolygonProof(4);m.scrub(1);assert.equal(m.progress,0);assert.ok(m.add(0,2));assert.ok(!m.add(1,3));m.scrub(1);assert.equal(m.progress,1);const bow=[{x:0,y:0},{x:100,y:100},{x:0,y:100},{x:100,y:0}];assert.equal(polygonError(bow),'simple');const concave=[{x:0,y:0},{x:100,y:0},{x:50,y:30},{x:100,y:100},{x:0,y:100}];assert.ok(triangulation(concave,[[1,3]]).error);m.move(0,{...m.points[1]});assert.equal(m.progress,0);assert.equal(m.cuts.length,0);});

test('canvas gesture ownership ignores outside gestures and blocks mixed origins until release',async()=>{
 const {installCanvasOwnership}=await import('../dist/interaction.js');const listeners=new Map(),canvas={addEventListener(){}};globalThis.document={addEventListener(type,fn){listeners.set(type,fn)},removeEventListener(type){listeners.delete(type)}};let cancelled=0;const owner=installCanvasOwnership(canvas,()=>cancelled++),down=(id,target)=>listeners.get('pointerdown')({pointerId:id,pointerType:'touch',target}),up=id=>listeners.get('pointerup')({pointerId:id});down(1,canvas);down(2,canvas);assert.equal(owner.allowed(),true);up(1);up(2);down(3,canvas);down(4,{});assert.equal(cancelled,1);assert.equal(owner.allowed(),false);let prevented=false;listeners.get('touchmove')({touches:[{},{}],cancelable:true,preventDefault(){prevented=true}});assert.ok(prevented);up(4);assert.equal(owner.allowed(),false);up(3);assert.equal(owner.allowed(),true);down(5,{});down(6,{});prevented=false;listeners.get('touchmove')({touches:[{},{}],cancelable:true,preventDefault(){prevented=true}});assert.equal(prevented,false);owner.dispose();delete globalThis.document;
});
